# Generated by Django 3.2.19 on 2023-06-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Dynasty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patternbank',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='0', max_length=100)),
                ('category', models.CharField(default='0', max_length=100)),
                ('species', models.CharField(default='0', max_length=100)),
                ('url', models.CharField(default='0', max_length=500)),
                ('image', models.BinaryField()),
                ('dynasty', models.CharField(default='0', max_length=100)),
                ('content', models.TextField()),
                ('patterns', models.CharField(default='0', max_length=100)),
            ],
        ),
    ]
