# Generated by Django 3.2.19 on 2023-06-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0002_category_dynasty_patternbank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patternbank',
            name='image',
        ),
    ]
