# Generated by Django 3.2.19 on 2023-06-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pattern', '0004_patternbank_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='patternbank',
            name='img_bytes',
            field=models.BinaryField(default=0),
        ),
    ]
