# Generated by Django 3.2.19 on 2023-06-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creativecenter', '0002_category_era_pattern'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pattern',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pattern',
            name='era',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Era',
        ),
        migrations.DeleteModel(
            name='Pattern',
        ),
    ]
